/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:eec11c68-5b60-4708-adf4-fc5a77937c77",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_jdCkd7Gcv",
    "aws_user_pools_web_client_id": "443nop80ib32gdk12pr85oscr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7swp23mz4rbcxlgo7yniojbfg4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3entomozyrarzlldtfzqh65kfy",
    "aws_user_files_s3_bucket": "gritsquad200552-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
